import { useLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import { cn } from '@/lib/utils'

import '../globals.css'
import type { Metadata } from 'next'
import { Rubik, Noto_Sans_Arabic } from 'next/font/google'

interface LocaleLayoutProps {
  children: React.ReactNode
  params: {
    locale: string
  }
}

const rubic = Rubik({ subsets: ['latin'] })
const noto = Noto_Sans_Arabic({ subsets: ['arabic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params }: LocaleLayoutProps) {
  const locale = useLocale()

  // Validate that the incoming `locale` parameter is a valid locale
  if (params.locale !== locale) {
    notFound()
  }

  return (
    <html lang={locale} dir={locale === 'fa' ? 'rtl' : 'ltr'}>
      <body className={cn(locale === 'fa' ? noto.className : rubic.className)}>
        {children}
      </body>
    </html>
  )
}
